resources:
  - fluentd.properties.yaml

namespace: fluentd

configMapGenerator:
  - name: fluentd-config
    files:
      - conf/fluent.conf
      - conf/apps.conf
      - conf/ingress.conf
      - conf/output.conf